include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    cascade_invocations: false
    use_key_in_widget_constructors: false
    prefer_int_literals: false
    public_member_api_docs: false
    use_if_null_to_convert_nulls_to_bools: false
